### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by pvqu47** [0xTowel/0xtowel.github.io#1]
Hi Peter! 
I have read your blog. Currently, I'm learning about invalid curve attack. In your post http://the2702.com/2015/05/08/invalid-curve-attack.html i don't understand how to choose a coefficient B' to new curve's order has small prime divisor. Can you explain it to me or show me how to choose B'. Thanks!

**Comment by 0xTowel** [comment]
Hi, it's been a while since I wrote that, but it seems like you should be able to just guess a few values and see which ones work. There's probably a smarter way, but that seems to be what I did in the writeup.
